sudo: required
services: 
  - docker
 
before_install:
  - docker build -t jitendra94/react-test -f ./client/Dockerfile.dev ./client
# if we want to build multple images from worker and client we cna give the same with different diractory

Script:
  -docker run -e CI=true jitendra94/react-test npm test
# if we want to run scripst give the same with test 

after_success:
# build production image 
  -docker build -t jitendra94/multi-client ./client
  -docker build -t jitendra94/multi-nginx ./nginx
  -docker build -t jitendra94/multi-server ./server
  -docker build -t jitendra94/multi-worker ./worker
  
#login docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take those images and push to dockerhub
  - docker push jitendra94/multi-client
  - docker push jitendra94/multi-nginx
  - docker push jitendra94/multi-server
  - docker push jitendra94/multi-worker
